"""The approval screen; tokens stay only in page memory, no third-party scripts."""
PAGE = r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>空投实验控制台</title><style>
body{font:16px/1.65 system-ui;margin:40px auto;padding:0 20px;max-width:1080px;background:#101820;color:#edf4f9}h1{font-size:28px}h2{font-size:20px;margin-top:32px}button,input{font:inherit;padding:9px 13px;border-radius:7px;border:1px solid #567;margin:4px}button{cursor:pointer;background:#d5edff;color:#16304b}input{background:#172c3c;color:white}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#193044;padding:18px;border-radius:10px}small{color:#a9bdce}.card{border:1px solid #426075;border-radius:12px;padding:20px;margin:16px 0}.danger{background:#ffc6c0}#message{color:#ffda83}.line{display:flex;gap:16px;flex-wrap:wrap}</style>
<h1>空投实验控制台</h1><p>寻找活动 → 算清成本 → 你批准 → 自动参与 → 对账复盘</p>
<p><small>未批准的方案不会执行。预计奖励不等于到账收入；“在线”也不等于已经参与活动。</small></p>
<div class="line"><input id="token" type="password" autocomplete="off" placeholder="控制台访问密钥"><button id="connect">读取状态</button><button id="pause" class="danger">暂停新增操作</button><button id="resume">恢复研究</button><button id="tick">运行一次检查</button></div>
<p id="message"></p><h2>运行情况</h2><pre id="status">尚未读取</pre><h2>待批准方案</h2><div id="proposals"></div>
<h2>候选活动与筛选结果</h2><div id="opportunities"></div><h2>账目</h2><pre id="ledger"></pre><h2>需要处理的事件</h2><pre id="events"></pre><h2>复盘</h2><pre id="reviews"></pre>
<script>
const $=id=>document.getElementById(id);const show=(id,value)=>$(id).textContent=JSON.stringify(value,null,2);
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+$('token').value,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;}
function message(s){$('message').textContent=s;}async function run(fn){try{await fn();}catch(e){message(e.message);}}
async function refresh(){const data=await api('status');show('status',data.runtime);show('ledger',data.ledger);show('events',data.events);show('reviews',data.reviews);$('proposals').replaceChildren();$('opportunities').replaceChildren();
for(const p of data.proposals){const card=document.createElement('div');card.className='card';const title=document.createElement('h3');title.textContent=p.id.slice(0,12)+' · '+p.state;card.append(title);const e=p.details.economics,plan=p.details.plan;const dollars=v=>v==null?'未知':(v/1000000).toFixed(2)+' 美元';const brief=document.createElement('p');brief.textContent='本金 '+dollars(e.principal_usd_micro)+'；预计全部费用 '+dollars(e.total_known_cost_usd_micro)+'；压力情景净收益 '+dollars(e.net_scenarios_usd_micro?.conservative)+'；本金全损加费用 '+dollars(e.worst_loss_usd_micro)+'。计划持有 '+e.days+' 天，入场批准有效至 '+new Date(plan.expires_at*1000).toLocaleString()+'。奖励可能为零。';card.append(brief);const full=document.createElement('details'),caption=document.createElement('summary'),pre=document.createElement('pre');caption.textContent='展开完整方案、费用明细、合约和退出规则';pre.textContent=JSON.stringify(p.details,null,2);full.append(caption,pre);card.append(full);
if(p.state==='pending_approval'){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode('我已核对活动、金额、全部费用、合约权限、有效期和退出条件，接受可能损失全部投入。'));card.append(label);const secret=document.createElement('input');secret.type='password';secret.autocomplete='off';secret.placeholder='独立执行器批准密钥（仅此次使用）';card.append(secret);const approve=document.createElement('button');approve.textContent='批准这个方案并开始执行';approve.onclick=()=>run(async()=>{if(!check.checked)throw Error('请先核对完整方案并勾选确认。');const result=await api('proposals/'+p.id+'/approve',{digest:p.digest,owner_token:secret.value});secret.value='';message('批准已记录：'+result.state);await refresh();});const reject=document.createElement('button');reject.textContent='拒绝';reject.onclick=()=>run(async()=>{await api('proposals/'+p.id+'/reject',{});await refresh();});card.append(approve,reject);} if(['approval_submitting','approved','executing','holding'].includes(p.state)){const secret=document.createElement('input');secret.type='password';secret.autocomplete='off';secret.placeholder='核对异常后输入独立批准密钥';const button=document.createElement('button');button.textContent='恢复这个已批准方案';button.onclick=()=>run(async()=>{try{await api('proposals/'+p.id+'/resume',{digest:p.digest,owner_token:secret.value});message('原方案已恢复；金额和权限没有扩大。');await refresh();}finally{secret.value='';}});card.append(secret,button);} $('proposals').append(card);}
for(const o of data.opportunities){const card=document.createElement('div');card.className='card';const title=document.createElement('strong');title.textContent=o.title+' · '+o.status;const pre=document.createElement('pre');pre.textContent=JSON.stringify({官方来源:o.url,核查时间:o.observed_at,分析:o.analysis},null,2);card.append(title,pre);$('opportunities').append(card);}}
$('connect').onclick=()=>run(refresh);$('pause').onclick=()=>run(async()=>{const r=await api('control',{paused:true});message(r.executor_paused?'已暂停；已广播交易仍需等待结果。':'研究已暂停，执行器暂停状态未能确认，请检查事件。');await refresh();});$('resume').onclick=()=>run(async()=>{await api('control',{paused:false});message('研究已恢复；资金操作仍须批准。');await refresh();});$('tick').onclick=()=>run(async()=>{const r=await api('tick',{});message('本次结果：'+JSON.stringify(r));await refresh();});
</script></html>'''
