"""The approval screen; tokens stay only in page memory, no third-party scripts."""
PAGE = r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>空投实验控制台</title><style>
body{font:16px/1.65 system-ui;margin:40px auto;padding:0 20px;max-width:1080px;background:#101820;color:#edf4f9}h1{font-size:28px}h2{font-size:20px;margin-top:32px}table{border-collapse:collapse;font-size:14px}td,th{border:1px solid #33506a;padding:4px 8px;text-align:left}button,input,select{font:inherit;padding:9px 13px;border-radius:7px;border:1px solid #567;margin:4px}button{cursor:pointer;background:#d5edff;color:#16304b}input{background:#172c3c;color:white}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#193044;padding:18px;border-radius:10px}small{color:#a9bdce}.card{border:1px solid #426075;border-radius:12px;padding:20px;margin:16px 0}.danger{background:#ffc6c0}#message{color:#ffda83}.line{display:flex;gap:16px;flex-wrap:wrap}</style>
<h1>空投实验控制台</h1><p>寻找活动 → 算清成本 → 你批准 → 自动参与 → 对账复盘</p>
<p><small>未批准的方案不会执行。预计奖励不等于到账收入；“在线”也不等于已经参与活动。</small></p>
<div class="line"><input id="token" type="password" autocomplete="off" placeholder="控制台访问密钥"><button id="connect">读取状态</button><button id="pause" class="danger">暂停新增操作</button><button id="resume">恢复研究</button><button id="tick">运行一次检查</button></div>
<p id="message"></p><h2>运行情况</h2><pre id="status">尚未读取</pre><h2>部署验收</h2><pre id="readiness">尚未读取</pre><h2>活动接入进度</h2><pre id="adapters">尚未读取</pre><h2>钱包接收器</h2><pre id="receiver">尚未读取</pre><h2>当前策略（按分类复盘）</h2><p><small id="rule"></small></p><div style="overflow-x:auto"><table id="cats"></table></div>
<h2>活动优先排序</h2><p><small>排序分 = 期望收益 × 分类权重；"优先级"越大越先处理，勾选"跳过"则不再分析。结果：抽奖没中奖请标"未中"，这样同类的中奖率才准。</small></p><div style="overflow-x:auto"><table id="ranking"></table></div>
<p><small>已因“账户不能参加”跳过的同类项目：<span id="blocked"></span></small></p>
<h2>我的设置（可在控制台修改）</h2><div class="card"><div class="line"><input id="st_hour" placeholder="每小时价值（美元）"><input id="st_addr" placeholder="钱包公开地址 0x…"><input id="st_rpc" placeholder="只读 RPC https://…"><input id="st_min" placeholder="最低期望收益（美元）"></div><p><small>分类先验与权重（p=得奖概率，payout_usd=得奖时金额，weight=排序权重）：</small></p><textarea id="st_priors" rows="8" style="width:100%;background:#172c3c;color:white;font:13px monospace"></textarea><button id="save_settings">保存设置</button><pre id="settings_view"></pre></div>
<h2>已实现收益与效率</h2><pre id="metrics">尚未读取</pre><h2>人工交接任务</h2><div id="handoffs"></div><h2>待批准资金方案</h2><div id="proposals"></div>
<h2>登记实际到账 / 实际费用</h2><div class="card"><small>只登记真实到账（有交易哈希或交易所记录）。奖池、积分、APR 不能登记为收入。</small><div class="line"><input id="in_ref" placeholder="来源（交接单/方案编号）"><input id="in_opp" placeholder="活动编号，如 galxe:xxx"><input id="in_asset" placeholder="资产，如 USDC"><input id="in_raw" placeholder="链上最小单位数量"><input id="in_dec" placeholder="小数位，如 6"><input id="in_usd" placeholder="美元价值"><select id="in_basis"><option value="stablecoin_1usd">稳定币按 1 美元</option><option value="exchange_sale_record">交易所卖出记录</option><option value="spot_at_receipt">到账时现价</option></select><input id="in_tx" placeholder="交易哈希 0x…（或填证据）"><input id="in_ev" placeholder="证据说明"><button id="add_income">登记到账</button></div><div class="line"><select id="c_cat"><option>gas</option><option>trading</option><option>slippage</option><option>bridge</option><option>exit</option><option>claim</option><option>ai</option><option>search_data</option><option>hosting</option><option>other</option></select><input id="c_opp" placeholder="活动编号（可选）"><input id="c_usd" placeholder="美元金额"><input id="c_tx" placeholder="交易哈希或账单证据"><button id="add_cost">登记费用</button></div></div>
<h2>候选活动与筛选结果</h2><div id="opportunities"></div><h2>AI 调用与费用</h2><pre id="model_runs"></pre><h2>账目</h2><pre id="ledger"></pre><h2>需要处理的事件</h2><pre id="events"></pre><h2>复盘</h2><pre id="reviews"></pre>
<script>
const $=id=>document.getElementById(id);const show=(id,value)=>$(id).textContent=JSON.stringify(value,null,2);
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+$('token').value,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;}
function message(s){$('message').textContent=s;}async function run(fn){try{await fn();}catch(e){message(e.message);}}
const micro=v=>Math.round(parseFloat(v)*1000000);
function handoffCard(h){const card=document.createElement('div');card.className='card';const t=document.createElement('h3');t.textContent=h.plan.title+' · '+h.state;const a=document.createElement('a');a.href=h.plan.url;a.textContent='打开官方页面';a.target='_blank';a.rel='noopener noreferrer';a.style.color='#9fd3ff';const pre=document.createElement('pre');pre.textContent=JSON.stringify({步骤:h.plan.steps,说明:h.plan.context},null,2);card.append(t,a,pre);
if(h.state==='pending_approval'){const ok=document.createElement('button');ok.textContent='批准交接（之后由我本人操作）';ok.onclick=()=>run(async()=>{await api('task-handoffs/'+h.id+'/approve',{digest:h.digest});await refresh();});const no=document.createElement('button');no.textContent='拒绝';no.onclick=()=>run(async()=>{await api('task-handoffs/'+h.id+'/reject',{});await refresh();});card.append(ok,no);}
if(h.state==='approved'){const ev=document.createElement('input');ev.placeholder='完成证据（截图说明/页面状态）';const mins=document.createElement('input');mins.placeholder='实际用时（分钟）';const done=document.createElement('button');done.textContent='标记已完成';done.onclick=()=>run(async()=>{const body={digest:h.digest,evidence:ev.value};if(mins.value)body.minutes=parseInt(mins.value,10);await api('task-handoffs/'+h.id+'/complete',body);await refresh();});card.append(ev,mins,done);}
return card;}
const usd=v=>v==null?'未知':'$'+Number(v).toFixed(2);const pct=v=>v==null?'—':(v*100).toFixed(0)+'%';
function cell(tr,v){const td=document.createElement('td');if(v instanceof Node)td.append(v);else td.textContent=v;tr.append(td);}
function head(t,cols){const tr=document.createElement('tr');cols.forEach(c=>{const th=document.createElement('th');th.textContent=c;tr.append(th);});t.append(tr);}
async function strategy(){const d=await api('strategy');$('rule').textContent=d.rule+' 共享 AI 成本：'+usd(d.shared_ai_cost_usd);
const c=$('cats');c.replaceChildren();head(c,['分类','发现','进行中','已完成','中奖率','到账','现金成本','人工分钟','时间成本','扣时间净额','当前概率','当前奖励','历史权重']);
for(const r of d.categories){const tr=document.createElement('tr');[r.label,r.discovered,r.in_progress,r.finished,pct(r.win_rate),usd(r.income_usd),usd(r.cash_cost_usd),r.human_minutes,usd(r.time_cost_usd),usd(r.net_after_time_usd),pct(r.current_p),usd(r.current_payout_usd),pct(r.history_weight)].forEach(v=>cell(tr,v));c.append(tr);}
const t=$('ranking');t.replaceChildren();head(t,['活动','分类','状态','期望收益','排序分','依据','优先级','跳过','结果','账户不能参加','']);
for(const r of d.ranking){const tr=document.createElement('tr');const a=document.createElement('a');a.href=r.url;a.textContent=r.title.slice(0,60);a.target='_blank';a.rel='noopener noreferrer';a.style.color='#9fd3ff';
const pr=document.createElement('input');pr.value=r.priority;pr.size=3;const sk=document.createElement('input');sk.type='checkbox';sk.checked=r.skipped;
const oc=document.createElement('select');[['','未知'],['paid','已到账'],['not_paid','未中/无奖励']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;if((r.outcome||'')===v)o.selected=true;oc.append(o);});
const ie=document.createElement('input');ie.type='checkbox';
const b=document.createElement('button');b.textContent='保存';b.onclick=()=>run(async()=>{const u={priority:parseInt(pr.value||'0',10),skip:sk.checked,outcome:oc.value||null};if(ie.checked)u.ineligible=true;await api('activities/'+encodeURIComponent(r.id),u);message('已保存：'+r.title+(ie.checked?'（同类项目以后跳过）':''));await strategy();});
[a,r.category,r.status,usd(r.ev_usd),r.score==null?'—':r.score.toFixed(2),r.basis||'—',pr,sk,oc,ie,b].forEach(v=>cell(tr,v));t.append(tr);}
$('blocked').textContent=d.ineligible_projects.length?d.ineligible_projects.map(x=>x.key).join('，'):'暂无';}
async function loadSettings(){const d=await api('settings');const e=d.effective;$('st_hour').value=e.human_hour_usd_micro==null?'':e.human_hour_usd_micro/1e6;$('st_addr').value=e.receiver_address||'';$('st_rpc').value=e.receiver_rpc_url||'';$('st_min').value=e.min_net_usd_micro==null?'':e.min_net_usd_micro/1e6;$('st_priors').value=JSON.stringify(e.category_priors||{},null,1);show('settings_view',d);window._ov=d.overrides;}
async function refresh(){await strategy();await loadSettings();const data=await api('status');show('metrics',await api('metrics'));$('handoffs').replaceChildren(...(await api('task-handoffs')).handoffs.map(handoffCard));show('status',data.runtime);show('readiness',await api('readiness'));show('receiver',await api('receiver'));show('adapters',await api('adapters'));show('ledger',data.ledger);show('model_runs',data.model_runs);show('events',data.events);show('reviews',data.reviews);$('proposals').replaceChildren();$('opportunities').replaceChildren();
for(const p of data.proposals){const card=document.createElement('div');card.className='card';const title=document.createElement('h3');title.textContent=p.id.slice(0,12)+' · '+p.state;card.append(title);const e=p.details.economics,plan=p.details.plan;const dollars=v=>v==null?'未知':(v/1000000).toFixed(2)+' 美元';const brief=document.createElement('p');brief.textContent='本金 '+dollars(e.principal_usd_micro)+'；预计全部费用 '+dollars(e.total_known_cost_usd_micro)+'；压力情景净收益 '+dollars(e.net_scenarios_usd_micro?.conservative)+'；本金全损加费用 '+dollars(e.worst_loss_usd_micro)+'。计划持有 '+e.days+' 天，入场批准有效至 '+new Date(plan.expires_at*1000).toLocaleString()+'。奖励可能为零。';card.append(brief);const full=document.createElement('details'),caption=document.createElement('summary'),pre=document.createElement('pre');caption.textContent='展开完整方案、费用明细、合约和退出规则';pre.textContent=JSON.stringify(p.details,null,2);full.append(caption,pre);card.append(full);
if(p.state==='pending_approval'){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode('我已核对活动、金额、全部费用、合约权限、有效期和退出条件，接受可能损失全部投入。'));card.append(label);const secret=document.createElement('input');secret.type='password';secret.autocomplete='off';secret.placeholder='独立执行器批准密钥（仅此次使用）';card.append(secret);const approve=document.createElement('button');approve.textContent='批准这个方案并开始执行';approve.onclick=()=>run(async()=>{if(!check.checked)throw Error('请先核对完整方案并勾选确认。');const result=await api('proposals/'+p.id+'/approve',{digest:p.digest,owner_token:secret.value});secret.value='';message('批准已记录：'+result.state);await refresh();});const reject=document.createElement('button');reject.textContent='拒绝';reject.onclick=()=>run(async()=>{await api('proposals/'+p.id+'/reject',{});await refresh();});card.append(approve,reject);} if(['approval_submitting','approved','executing','holding'].includes(p.state)){const secret=document.createElement('input');secret.type='password';secret.autocomplete='off';secret.placeholder='核对异常后输入独立批准密钥';const button=document.createElement('button');button.textContent='恢复这个已批准方案';button.onclick=()=>run(async()=>{try{await api('proposals/'+p.id+'/resume',{digest:p.digest,owner_token:secret.value});message('原方案已恢复；金额和权限没有扩大。');await refresh();}finally{secret.value='';}});card.append(secret,button);} $('proposals').append(card);}
for(const o of data.opportunities){const card=document.createElement('div');card.className='card';const title=document.createElement('strong');title.textContent=o.title+' · '+o.status;const pre=document.createElement('pre');pre.textContent=JSON.stringify({官方来源:o.url,资料时间:new Date(o.observed_at*1000).toLocaleString(),固定规则筛选:o.screening,AI分析:o.analysis},null,2);card.append(title,pre);if(o.id.startsWith('galxe:')){const button=document.createElement('button');button.textContent='自动查询我的资格（不参与、不签名）';button.onclick=()=>run(async()=>{const result=await api('adapters/galxe/check',{opportunity_id:o.id});message('资格查询：'+JSON.stringify(result));await refresh();});card.append(button);}$('opportunities').append(card);}}
$('connect').onclick=()=>run(refresh);$('save_settings').onclick=()=>run(async()=>{const o={...(window._ov||{})};const n=(id,k,f)=>{const v=$(id).value.trim();if(v==='')delete o[k];else o[k]=f(v);};n('st_hour','human_hour_usd_micro',v=>Math.round(parseFloat(v)*1e6));n('st_addr','receiver_address',v=>v);n('st_rpc','receiver_rpc_url',v=>v);n('st_min','min_net_usd_micro',v=>Math.round(parseFloat(v)*1e6));if(o.receiver_address&&!o.receiver_chain_id)o.receiver_chain_id=1;try{o.category_priors=JSON.parse($('st_priors').value||'{}');}catch(e){throw Error('分类先验不是有效 JSON');}await api('settings',{overrides:o});message('设置已保存，下次运行生效');await loadSettings();});$('add_income').onclick=()=>run(async()=>{const b={source_ref:$('in_ref').value,asset:$('in_asset').value,amount_raw:$('in_raw').value,decimals:parseInt($('in_dec').value,10),usd_micro:micro($('in_usd').value),price_basis:$('in_basis').value};if($('in_opp').value)b.opportunity_id=$('in_opp').value;if($('in_tx').value.startsWith('0x'))b.tx_hash=$('in_tx').value;if($('in_ev').value)b.evidence=$('in_ev').value;const r=await api('ledger/income',b);message('已登记到账；当前已实现净收益 '+(r.realized.realized_net_usd_micro/1e6).toFixed(2)+' 美元');await refresh();});$('add_cost').onclick=()=>run(async()=>{const b={category:$('c_cat').value,usd_micro:micro($('c_usd').value)};if($('c_opp').value)b.opportunity_id=$('c_opp').value;const x=$('c_tx').value;if(/^0x[0-9a-fA-F]{64}$/.test(x))b.tx_hash=x;else b.evidence=x;const r=await api('ledger/cost',b);message('已登记费用；当前已实现净收益 '+(r.realized.realized_net_usd_micro/1e6).toFixed(2)+' 美元');await refresh();});$('pause').onclick=()=>run(async()=>{const r=await api('control',{paused:true});message(r.executor_paused?'已暂停；已广播交易仍需等待结果。':'研究已暂停，执行器暂停状态未能确认，请检查事件。');await refresh();});$('resume').onclick=()=>run(async()=>{await api('control',{paused:false});message('研究已恢复；资金操作仍须批准。');await refresh();});$('tick').onclick=()=>run(async()=>{const r=await api('tick',{});message('本次结果：'+JSON.stringify(r));await refresh();});
</script></html>'''
